# Dependencies
markdown:         GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Crist처v찾o Rufino's Blog
tagline:          'My DIY stories'
description:      'This blog is dedicated to stuff I do on my projects'
url:              https://cristovaozr.github.io
baseurl:          https://cristovaozr.github.io/

author:
  name:           'Crist처v찾o Zuppardo Rufino'
  url:            https://linkedin.com/in/cristovaozr

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/cristovaozr
