title: Blog - Cristóvão Rufino
description: "Linux, embedded systems, DIY and more..."
author:
  name: "Cristóvão Rufino"
  # email: "someone@somewebsite.somedomain"
  url: "cristovaozr.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner :         "cristovaozr"
ownerFullName : "Cristóvão Rufino"
year :          "2019"
hostname :      "github.io"